# Hand-written partial stubs for libusb1 (no upstream stubs, no types-libusb1 on pypi),
# covering only the surface used by docker/aoa-bridge/src/aoa_bridge/main.py.

from collections.abc import Callable, Iterator
from types import TracebackType
from typing import Self

class USBError(Exception): ...

TRANSFER_COMPLETED: int
TRANSFER_CANCELLED: int

class USBEndpoint:
    def getAddress(self) -> int: ...

class USBInterfaceSetting:
    def iterEndpoints(self) -> Iterator[USBEndpoint]: ...

class USBInterface:
    def __getitem__(self, index: int) -> USBInterfaceSetting: ...

class USBConfiguration:
    def __getitem__(self, index: int) -> USBInterface: ...

class USBTransfer:
    def setBulk(
        self,
        endpoint: int,
        buffer_or_len: int | bytes | bytearray,
        callback: Callable[[USBTransfer], None] | None = None,
        user_data: object | None = None,
        timeout: int = 0,
    ) -> None: ...
    def submit(self) -> None: ...
    def cancel(self) -> None: ...
    def isSubmitted(self) -> bool: ...
    def getStatus(self) -> int: ...
    def getActualLength(self) -> int: ...
    def getBuffer(self) -> bytearray: ...

class USBDevice:
    def getVendorID(self) -> int: ...
    def getProductID(self) -> int: ...
    def getDeviceClass(self) -> int: ...
    def open(self) -> USBDeviceHandle: ...
    def iterConfigurations(self) -> Iterator[USBConfiguration]: ...

class USBDeviceHandle:
    def getDevice(self) -> USBDevice: ...
    def kernelDriverActive(self, interface: int) -> bool: ...
    def detachKernelDriver(self, interface: int) -> None: ...
    def claimInterface(self, interface: int) -> object: ...
    def controlRead(
        self,
        request_type: int,
        request: int,
        value: int,
        index: int,
        length: int,
        timeout: int = 0,
    ) -> bytearray: ...
    def controlWrite(
        self,
        request_type: int,
        request: int,
        value: int,
        index: int,
        data: bytes,
        timeout: int = 0,
    ) -> int: ...
    def bulkWrite(self, endpoint: int, data: bytes, timeout: int = 0) -> int: ...
    def getTransfer(self) -> USBTransfer: ...
    def resetDevice(self) -> None: ...
    def close(self) -> None: ...

class USBContext:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def openByVendorIDAndProductID(
        self,
        vendor_id: int,
        product_id: int,
        skip_on_error: bool = False,
    ) -> USBDeviceHandle | None: ...
    def getDeviceList(self, skip_on_error: bool = False) -> list[USBDevice]: ...
    def handleEventsTimeout(self, tv: float = 0) -> None: ...
